<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace" nsURI="http://www.gemoc.org/generic_trace" nsPrefix="trace">
  <eClassifiers xsi:type="ecore:EDataType" name="ISerializable" instanceClassName="byte[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="MSEOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mse" lowerBound="1" eType="#//MSE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSE" abstract="true" eSuperTypes="../../org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement">
    <eOperations name="getCaller" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eOperations name="getAction" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSEModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMSEs" upperBound="-1"
        eType="#//MSE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericMSE" eSuperTypes="#//MSE">
    <eOperations name="getCaller" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return callerReference;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAction" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return actionReference;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callerReference" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionReference" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" abstract="true">
    <eTypeParameters name="TracedObjectSubtype">
      <eBounds eClassifier="#//TracedObject">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedObjects" ordered="false"
        upperBound="-1" containment="true">
      <eGenericType eTypeParameter="#//Trace/TracedObjectSubtype"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//Trace/StateSubType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="launchconfiguration" lowerBound="1"
        eType="ecore:EClass LaunchConfiguration.ecore#//LaunchConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedObject" abstract="true">
    <eTypeParameters name="DimensionSubType">
      <eBounds eClassifier="#//Dimension">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eOperations name="getDimensionsInternal" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="// Default implementation, returning empty list.&#xA;final EList&lt;DimensionSubType> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;DimensionSubType>(Object.class);&#xA;return result;"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//TracedObject/DimensionSubType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="get" value="return getDimensionsInternal();"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//TracedObject/DimensionSubType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension" abstract="true">
    <eTypeParameters name="ValueSubType">
      <eBounds eClassifier="#//Value">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//Dimension/ValueSubType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true">
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eOpposite="#//State/values">
      <eGenericType eTypeParameter="#//Value/StateSubType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true">
    <eTypeParameters name="ValueSubType">
      <eBounds eClassifier="#//Value">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" ordered="false"
        upperBound="-1" eOpposite="#//Value/states">
      <eGenericType eTypeParameter="#//State/ValueSubType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepmark" eType="#//StepMark"
        eOpposite="#//StepMark/state"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepStart" eSuperTypes="#//StepMark">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ends" upperBound="-1" eType="#//StepEnd"
        eOpposite="#//StepEnd/start"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mseoccurrence" eType="#//MSEOccurrence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepMark" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outTransition" eType="#//StepTransition"
        eOpposite="#//StepTransition/previousStepMark"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="#//State"
        eOpposite="#//State/stepmark"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inTransition" eType="#//StepTransition"
        eOpposite="#//StepTransition/nextStepMarks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepEnd" eSuperTypes="#//StepMark">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//StepStart"
        eOpposite="#//StepStart/ends"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousStepMark" upperBound="-1"
        eType="#//StepMark" eOpposite="#//StepMark/outTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStepMarks" upperBound="-1"
        eType="#//StepMark" eOpposite="#//StepMark/inTransition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//StepTransitionType"
        defaultValueLiteral="SINGLE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StepTransitionType">
    <eLiterals name="AND"/>
    <eLiterals name="XOR" value="1"/>
    <eLiterals name="SINGLE" value="2"/>
    <eLiterals name="JOIN" value="3"/>
  </eClassifiers>
</ecore:EPackage>
